Tablero_Interactivo/Tablero_Interactivo/urls.py
from django.contrib import admin
from django.urls import path,include
from homicidios.views import dashboard  # Asegúrate de importar la vista del dashboard

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homicidios.urls')),  # Incluye todas las URLs de homicidios en la raíz
]

Tablero_Interactivo/homicidios/urls.py
# homicidios/urls.py
from django.urls import path
from . import views

app_name = 'homicidios'  # Define el namespace

urlpatterns = [
    path('', views.dashboard, name='dashboard'),  # Ruta para el dashboard
    path('detalle_homicidios/<str:entidad_nombre>/', views.detalle_homicidios, name='detalle_homicidios'),
    path('mostrar/', views.mostrar_homicidios, name='mostrar_homicidios'),
]

Tablero_Interactivo/homicidios/models.py
# models.py
from django.db import models

class Entidad(models.Model):
    nombre = models.CharField(max_length=100)

class Municipio(models.Model):
    nombre = models.CharField(max_length=100)
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)

class Fuente(models.Model):
    nombre = models.CharField(max_length=100)

class Homicidio(models.Model):
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    fecha = models.DateField()
    total = models.IntegerField()  # Campo para almacenar el total de homicidios
    fuente = models.ForeignKey(Fuente, on_delete=models.CASCADE, null=True, blank=True)


class EstadisticaDiaria(models.Model):
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    fecha = models.DateField()
    total_homicidios = models.IntegerField()

Tablero_Interactivo/homicidios/views.py
import json
from django.shortcuts import render, get_object_or_404
from django.conf import settings
import os
from django.db.models import Sum
import plotly.graph_objects as go
from .models import EstadisticaDiaria, Entidad
from plotly.utils import PlotlyJSONEncoder  # Importación correcta
from .models import Homicidio, Entidad
from django.db.models.functions import ExtractMonth,ExtractYear



def dashboard(request):
    # Obtener parámetros de filtro desde la solicitud GET
    start_year = request.GET.get('start_year', None)
    end_year = request.GET.get('end_year', None)
    chart_type = request.GET.get('chart_type', 'porMes')  # Por defecto, 'porMes'

    # Lista de nombres de estados válidos
    estados_validos = [
        "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua",
        "Ciudad de México", "Coahuila", "Colima", "Durango", "Estado de México", "Guanajuato", "Guerrero",
        "Hidalgo", "Jalisco", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla",
        "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas",
        "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"
    ]

    # Filtrar homicidios por año si están seleccionados
    homicidios_data = Homicidio.objects.filter(entidad__nombre__in=estados_validos)
    if start_year:
        homicidios_data = homicidios_data.filter(fecha__year__gte=start_year)
    if end_year:
        homicidios_data = homicidios_data.filter(fecha__year__lte=end_year)

    # Agregar lógica según el tipo de gráfica (si es necesario)
    homicidios_data = homicidios_data.values('entidad__nombre').annotate(total_homicidios=Sum('total')).all()


    # Crear un diccionario de homicidios por entidad
    homicidios_dict = {item['entidad__nombre']: item['total_homicidios'] for item in homicidios_data}

    # Lista de entidades (estados) y coordenadas de los estados
    coordenadas_estados = {
        "Aguascalientes": (21.8833, -102.2916),
        "Baja California": (32.6519, -115.4683),
        "Baja California Sur": (24.1426, -110.3107),
        "Campeche": (19.8454, -90.5238),
        "Chiapas": (16.7569, -93.1292),
        "Chihuahua": (28.6321, -106.0691),
        "Ciudad de México": (19.4326, -99.1332),
        "Coahuila": (27.0587, -101.7068),
        "Colima": (19.2433, -103.7250),
        "Durango": (24.0226, -104.6576),
        "Estado de México": (19.3286, -99.6760),
        "Guanajuato": (21.0190, -101.2574),
        "Guerrero": (17.4392, -99.5451),
        "Hidalgo": (20.0911, -98.7624),
        "Jalisco": (20.6767, -103.3475),
        "Michoacán": (19.7008, -101.1844),
        "Morelos": (18.6813, -99.1013),
        "Nayarit": (21.7514, -104.8455),
        "Nuevo León": (25.6866, -100.3161),
        "Oaxaca": (17.0732, -96.7266),
        "Puebla": (19.0413, -98.2062),
        "Querétaro": (20.5888, -100.3899),
        "Quintana Roo": (19.1817, -88.4791),
        "San Luis Potosí": (22.1565, -100.9855),
        "Sinaloa": (24.8044, -107.4937),
        "Sonora": (29.0729, -110.9559),
        "Tabasco": (17.9897, -92.9475),
        "Tamaulipas": (24.2669, -98.8363),
        "Tlaxcala": (19.3190, -98.1997),
        "Veracruz": (19.1738, -96.1342),
        "Yucatán": (20.6846, -89.1860),
        "Zacatecas": (22.7709, -102.5832)
    }

    # Configurar el gráfico
    fig = go.Figure()
    escala_tamano = 0.1
    tamano_max = 50

    # Añadir los datos al gráfico
    for entidad, homicidios in homicidios_dict.items():
        lat, lon = coordenadas_estados.get(entidad, (0, 0))
        tamano = min(10 + homicidios * escala_tamano, tamano_max)
        url = f"/detalle_homicidios/{entidad}/"  # Construir la URL dinámica

        fig.add_trace(go.Scattermapbox(
            lat=[lat],
            lon=[lon],
            mode='markers',
            marker=go.scattermapbox.Marker(
                size=tamano,
                color='red'
            ),
            text=f"{entidad}: {homicidios} homicidios",
            name=entidad,
            customdata = [url]  # Guardar la URL en customdata
        ))

    # Configurar el layout del mapa
    fig.update_layout(
        autosize=True,
        hovermode='closest',
        mapbox=dict(
            style='open-street-map',
            bearing=0,
            center=dict(lat=23.6345, lon=-102.5528),
            pitch=0,
            zoom=5
        ),
        margin=dict(l=0, r=0, t=0, b=0)
    )

    # Convertir el gráfico a formato JSON
    graph_json = json.dumps(fig, cls=PlotlyJSONEncoder)

    # Crear gráfico de barras
    bar_fig = go.Figure(data=[
        go.Bar(
            x=list(homicidios_dict.keys()),
            y=list(homicidios_dict.values()),
            marker=dict(color='#611232'),
            text=[f"{estado}: {total}" for estado, total in homicidios_dict.items()],
            textposition="auto",
        )
    ])
    bar_fig.update_layout(
        title="Total de Homicidios por Entidad",
        xaxis_title="Entidades",
        yaxis_title="Total de Homicidios",
        margin=dict(l=40, r=40, t=40, b=80),
        height=400
    )
    bar_graph_json = json.dumps(bar_fig, cls=PlotlyJSONEncoder)

    # Pasar el año seleccionado y el gráfico al contexto
    return render(request, 'homicidios/dashboard.html', {
        'graph_json': graph_json,
        'bar_graph_json': bar_graph_json,
        'selected_start_year': start_year,
        'selected_end_year': end_year,
        'chart_type': chart_type,
        'years': range(2019, 2025)  # Años de 2019 a 2024
    })


def mostrar_homicidios(request):
    homicidios = Homicidio.objects.all()
    return render(request, 'homicidios/mostrar_homicidios.html', {'homicidios': homicidios})

def detalle_homicidios(request, entidad_nombre):
    # Obtener entidad seleccionada
    entidad = get_object_or_404(Entidad, nombre=entidad_nombre)

    # Obtener año seleccionado del formulario
    selected_year = request.GET.get('year')

    # Filtrar los homicidios de esta entidad
    homicidios = Homicidio.objects.filter(entidad=entidad)

    # Si se seleccionó un año, filtrar los homicidios por ese año
    if selected_year:
        homicidios = homicidios.filter(fecha__year=selected_year)

    # Obtener todos los años disponibles para el filtro
    anios_disponibles = Homicidio.objects.annotate(anio=ExtractYear('fecha')).values_list('anio', flat=True).distinct()

    # Datos para el gráfico de líneas (homicidios por mes a lo largo del tiempo)
    homicidios_por_mes = (
        homicidios
        .annotate(mes=ExtractMonth('fecha'), anio=ExtractYear('fecha'))
        .values('mes', 'anio')
        .annotate(total_homicidios=Sum('total'))
        .order_by('anio', 'mes')
    )

    # Eje X y Y para el gráfico de líneas
    x_data = [f"{dato['anio']}-{dato['mes']:02d}" for dato in homicidios_por_mes]
    y_data = [dato['total_homicidios'] for dato in homicidios_por_mes]

    line_fig = go.Figure(data=[
        go.Scatter(x=x_data, y=y_data, mode='lines+markers', marker=dict(color='blue'))
    ])
    line_fig.update_layout(
        title=f"Homicidios por Mes en {entidad.nombre}",
        xaxis_title="Fecha",
        yaxis_title="Total de Homicidios",
        margin=dict(l=40, r=40, t=40, b=40)
    )
    line_graph_json = json.dumps(line_fig, cls=PlotlyJSONEncoder)

    # Datos para el gráfico de barras (homicidios totales por año)
    homicidios_por_anio = (
        homicidios
        .annotate(anio=ExtractYear('fecha'))
        .values('anio')
        .annotate(total_homicidios=Sum('total'))
        .order_by('anio')
    )

    bar_x_data = [dato['anio'] for dato in homicidios_por_anio]
    bar_y_data = [dato['total_homicidios'] for dato in homicidios_por_anio]

    bar_fig = go.Figure(data=[
        go.Bar(x=bar_x_data, y=bar_y_data, marker=dict(color='orange'))
    ])
    bar_fig.update_layout(
        title=f"Homicidios Totales por Año en {entidad.nombre}",
        xaxis_title="Año",
        yaxis_title="Total de Homicidios",
        margin=dict(l=40, r=40, t=40, b=40)
    )
    bar_graph_json = json.dumps(bar_fig, cls=PlotlyJSONEncoder)

    # Renderizar la plantilla
    return render(request, 'homicidios/detalle_homicidios.html', {
        'homicidios': homicidios,
        'entidad': entidad,
        'line_graph_json': line_graph_json,
        'bar_graph_json': bar_graph_json,
        'anios_disponibles': sorted(anios_disponibles),
        'selected_year': selected_year
    })

Tablero_Interactivo/homicidios/templates/homicidios/dashboard.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tablero Interactivo de Homicidios</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f5eddb;
            font-family: "Montserrat";
            margin: 0;
            padding: 0;
        }
        .header {
            background-color: #611232;
            color: white;
            padding: 10px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            width: 100%;
            box-sizing: border-box;
            margin: 0;
        }
        .header-left {
            display: flex;
            align-items: center;
        }
        .header-left img {
            height: 50px;
            margin-right: 15px;
        }
        .header-right {
            text-align: right;
        }
        .content {
            display: flex;
            justify-content: space-between;
            padding: 20px;
            gap: 20px;
        }
        .form-container {
            background-color: white;
            width: 1065px;
            height: 768px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }
        .options-container {
            background-color: #e9e9e9;
            width: 100%;
            height: 110px;
            display: flex;
            align-items: center;
            justify-content: flex-start;
            padding: 0 20px;
            gap: 15px;
            border-bottom: 1px solid #ccc;
        }
        .options-container div {
            display: flex;
            flex-direction: column;
        }
        .options-container label {
            margin-bottom: 5px;
            font-size: 0.9rem;
        }
        .map-container {
            background-color: #ddd;
            border: 2px solid #ddd;
            border-radius: 10px;
            width: 735px;
            height: 768px;
            box-sizing: border-box;
            overflow: hidden;
            padding: 10px;
        }
        .row {
            display: flex;
            gap: 10px;
            margin-bottom: 10px;
        }
        .col {
            flex: 1;
        }
        button {
            padding: 10px 20px;
            background-color: #611232;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        button:hover {
            background-color: #500e29;
        }

        table {
        width: 100%;
        border-spacing: 10px; /* Espacio entre celdas */
        }
        table td {
            vertical-align: top;
        }
        .btn {
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    font-size: 0.9rem;
    text-align: center;
}

.btn-primary {
    background-color: #611232;
    color: white;
}

.btn-primary:hover {
    background-color: #500e29;
}

.btn-secondary {
    background-color: #ccc;
    color: black;
    text-decoration: none;
}

.btn-secondary:hover {
    background-color: #aaa;
}

    </style>
</head>
<body>
    <div class="header">
        <div class="header-left">
            <img src="../../../static/logo-mexico.png" alt="Gobierno de México">
        </div>
        <div class="header-right">
            <h1>Tablero Interactivo de Homicidios Dolosos</h1>
        </div>
    </div>

    <div class="content">
        <!-- Contenedor para los switches -->
        <div class="form-container">
            <div class="options-container">
                <form method="GET" action="{% url 'homicidios:dashboard' %}">
                    <table>
                        <tr>
                            <td>
                                <label for="start_year">Fecha Inicial</label>
                                <select name="start_year" id="start_year">
                                    <option value="">Año</option>
                                    {% for year in years %}
                                        <option value="{{ year }}" {% if selected_start_year == year|stringformat:"s" %}selected{% endif %}>{{ year }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td>
                                <label for="end_year">Fecha Final</label>
                                <select name="end_year" id="end_year">
                                    <option value="">Año</option>
                                    {% for year in years %}
                                        <option value="{{ year }}" {% if selected_end_year == year|stringformat:"s" %}selected{% endif %}>{{ year }}</option>
                                    {% endfor %}
                                </select>
                            </td>

                            <td>
                                <button type="submit" class="btn btn-primary">OK</button>
                            </td>
                            <td>
                                <!-- Botón para restablecer los filtros con un icono -->
                                <a href="{% url 'homicidios:dashboard' %}"
                                   class="btn btn-secondary"
                                   style="padding: 10px; border-radius: 50%; background-color: transparent; border: none; display: inline-block;">
                                    <i class="fas fa-redo" style="font-size: 20px; color: black;"></i>
                                </a>
                            </td>
                        </tr>
                    </table>
                </form>
            </div>

        <div id="chart-container" style="padding: 20px; height: 500px; overflow: hidden;">
        <!-- Aquí se renderizará la gráfica -->
        <div id="chart" style="width: 100%; height: 100%;"></div>
        </div>
        </div>

        <!-- Contenedor para el mapa -->
        <div class="map-container" id="map">
            <!-- Mapa dinámico -->
        </div>
    </div>

    <!-- Incluir Plotly -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

    <!-- Código JavaScript para renderizar el mapa -->
    <script>
        var graphJSON = {{ graph_json|safe }};
        Plotly.newPlot('map', graphJSON, {
            geo: {
                scope: 'north america', // Limitar la vista a América del Norte
                projection: {
                    type: 'mercator'
                },
                center: {
                    lon: -102.5528, // Centrar en México
                    lat: 23.6345
                },
                fitbounds: "locations", // Ajustar al tamaño de México
                showland: true,
                landcolor: "#f5f5f5",
                showlakes: true,
                lakecolor: "#cce5ff",
                showcountries: true,
                countrycolor: "#ccc",
                subunitcolor: "#666" // Líneas divisorias
            },
            margin: { t: 0, l: 0, r: 0, b: 0 },
        });
        // Renderizar el gráfico de barras
        var barGraphJSON = {{ bar_graph_json|safe }};
        Plotly.newPlot('chart', barGraphJSON);
        var mapElement = document.getElementById('map');
        mapElement.on('plotly_click', function(data) {
            if (data.points.length > 0) {
                    // Obtener la URL desde customdata
                    var url = data.points[0].customdata;
                    if (url) {
                        window.location.href = url; // Redirigir a la URL
                    }
                }
            });
    </script>
</body>
</html>

Tablero_Interactivo/homicidios/templates/homicidios/detalle_homicidios.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tablero Interactivo de Homicidios</title>
    <style>
        body {
            background-color: #f5eddb;
            font-family: "Montserrat";
            margin: 0;
            padding: 0;
        }
        .header {
            background-color: #611232;
            color: white;
            padding: 10px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            width: 100%;
            box-sizing: border-box;
            margin: 0;
        }
        .header-left {
            display: flex;
            align-items: center;
        }
        .header-left img {
            height: 50px;
            margin-right: 15px;
        }
        .header-right {
            text-align: right;
        }
        .content {
            display: flex;
            justify-content: center;
            padding: 20px;
        }
        .form-container {
            background-color: white;
            width: 100%;
            height: auto;
            box-sizing: border-box;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            padding: 20px;
        }
        .chart-container {
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="header-left">
            <img src="../../../static/logo-mexico.png" alt="Gobierno de México">
        </div>
        <div class="header-right">
            <h1>Tablero Interactivo de Homicidios Dolosos</h1>
        </div>
    </div>

    <div class="content">
        <div class="form-container">
            <!-- Título de la entidad -->
            <h1>Homicidios en {{ entidad.nombre }}</h1>

            <form method="GET" action="" id="yearFilterForm">
                <label for="year">Seleccionar Año:</label>
                <select name="year" id="year" onchange="this.form.submit();">
                    <option value="">Todos los años</option>
                    {% for anio in anios_disponibles %}
                    <option value="{{ anio }}" {% if anio|stringformat:"s" == selected_year %}selected{% endif %}>{{ anio }}</option>
                    {% endfor %}
                </select>
            </form>

            <!-- Contenedor para el gráfico de líneas -->
            <div id="line_graph" class="chart-container" style="width: 100%; height: 400px;"></div>

            <!-- Contenedor para el gráfico de barras -->
            <div id="bar_graph" class="chart-container" style="width: 100%; height: 400px;"></div>
        </div>
    </div>

    <!-- Incluir scripts de Plotly -->
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        // Gráfico de líneas
        var lineGraph = {{ line_graph_json|safe }};
        Plotly.newPlot('line_graph', lineGraph);

        // Gráfico de barras
        var barGraph = {{ bar_graph_json|safe }};
        Plotly.newPlot('bar_graph', barGraph);
    </script>
</body>
</html>

Tablero_Interactivo/homicidios/templates/homicidios/mostrar_homicidios.html
<!-- homicidios/templates/homicidios/mostrar_homicidios.html -->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Lista de Homicidios</title>
</head>
<body>
    <h1>Lista de Homicidios</h1>
    <ul>
    {% for homicidio in homicidios %}
        <li>{{ homicidio.entidad.nombre }} - {{ homicidio.fecha }} - {{ homicidio.total }}</li>
    {% endfor %}
    </ul>
</body>
</html>